version: '3.8'

services:
  # Banco de Dados Relacional (PostgreSQL)
  postgres_db:
    image: postgres:16-alpine
    container_name: sman_postgres
    environment:
      POSTGRES_USER: sman_user
      POSTGRES_PASSWORD: sman_password
      POSTGRES_DB: sman_core
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Banco de Dados NoSQL (MongoDB para Telemetria)
  mongo_db:
    image: mongo:7.0
    container_name: sman_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: sman_admin
      MONGO_INITDB_ROOT_PASSWORD: sman_admin_password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Backend da Aplicação (Node.js)
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: sman_backend
    volumes:
      - ./src/backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://sman_admin:sman_admin_password@mongo_db:27017/sman_telemetry?authSource=admin
      - POSTGRES_URI=postgresql://sman_user:sman_password@postgres_db:5432/sman_core
    depends_on:
      - postgres_db
      - mongo_db

  # Frontend da Aplicação (React + Vite)
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: sman_frontend
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

  # Broker MQTT (Eclipse Mosquitto para comunicação IoT)
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: sman_mosquitto
    ports:
      - "1883:1883" # Porta padrão MQTT
      - "9001:9001" # Porta para WebSockets (útil no futuro)
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

volumes:
  postgres_data:
  mongo_data:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
